import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
await mkdir('public/vendor',{recursive:true});
await build({stdin:{contents:"export {createClient} from '@supabase/supabase-js';",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'browser',target:'es2022',outfile:'public/vendor/supabase.js',minify:true,legalComments:'eof'});
const html=await readFile('public/index.html','utf8');
const core=new Set(['/','/manifest.webmanifest','/icons/icon-192.png','/icons/icon-512.png','/kickpot-hero-final.jpg']);
for(const m of html.matchAll(/(?:src|href)="(\/[^"?]+)(?:\?[^"]*)?"/g))core.add(m[1]);
const visited=new Set();
const walk=async p=>{if(visited.has(p))return;visited.add(p);core.add(p);const source=await readFile('public'+p,'utf8');
 for(const m of source.matchAll(/(?:from\s*|import\s*\(?)['"]\.\/([^'"]+\.js)['"]/g))await walk('/'+m[1]);
 if(p.endsWith('.css'))for(const m of source.matchAll(/url\(['"]?(\/[^)'"?]+)(?:\?[^)'"\s]*)?['"]?\)/g)){
   core.add(m[1]);if(m[1].endsWith('.css'))await walk(m[1]);
 }
};
core.add('/supabase-singleton.js');
for(const p of [...core])if(/\.(js|css)$/.test(p))await walk(p);
const files=[...core].sort();const hash=createHash('sha256');
for(const p of files)hash.update(await readFile('public'+(p==='/'?'/index.html':p)));
hash.update(await readFile('scripts/sw-template.js'));
const template=await readFile('scripts/sw-template.js','utf8');
await writeFile('public/sw.js',`// Generated by npm run build.\nconst CACHE='kickpot-${hash.digest('hex').slice(0,16)}';\nconst CORE=${JSON.stringify(files)};\n`+template);
console.log(`Built local SDK and verified ${files.length} offline assets.`);
